//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 02:05:01 PM MST 
//


package gov.inl.igcapt.gdtaf.gucs;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.inl.igcapt.gdtaf.gucs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.inl.igcapt.gdtaf.gucs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GDTAF }
     * 
     */
    public GDTAF createGDTAF() {
        return new GDTAF();
    }

    /**
     * Create an instance of {@link GridCommunicationPath }
     * 
     */
    public GridCommunicationPath createGridCommunicationPath() {
        return new GridCommunicationPath();
    }

    /**
     * Create an instance of {@link GridUseCaseScenario }
     * 
     */
    public GridUseCaseScenario createGridUseCaseScenario() {
        return new GridUseCaseScenario();
    }

    /**
     * Create an instance of {@link GDTAF.GridUseCaseScenarioRepo }
     * 
     */
    public GDTAF.GridUseCaseScenarioRepo createGDTAFGridUseCaseScenarioRepo() {
        return new GDTAF.GridUseCaseScenarioRepo();
    }

    /**
     * Create an instance of {@link GDTAF.ApplicationScenarioRepo }
     * 
     */
    public GDTAF.ApplicationScenarioRepo createGDTAFApplicationScenarioRepo() {
        return new GDTAF.ApplicationScenarioRepo();
    }

    /**
     * Create an instance of {@link GDTAF.OperationalObjectiveRepo }
     * 
     */
    public GDTAF.OperationalObjectiveRepo createGDTAFOperationalObjectiveRepo() {
        return new GDTAF.OperationalObjectiveRepo();
    }

    /**
     * Create an instance of {@link GDTAF.PayloadRepo }
     * 
     */
    public GDTAF.PayloadRepo createGDTAFPayloadRepo() {
        return new GDTAF.PayloadRepo();
    }

    /**
     * Create an instance of {@link GDTAF.GridCommunicationPathRepo }
     * 
     */
    public GDTAF.GridCommunicationPathRepo createGDTAFGridCommunicationPathRepo() {
        return new GDTAF.GridCommunicationPathRepo();
    }

    /**
     * Create an instance of {@link GDTAF.RequirementRepo }
     * 
     */
    public GDTAF.RequirementRepo createGDTAFRequirementRepo() {
        return new GDTAF.RequirementRepo();
    }

    /**
     * Create an instance of {@link GDTAF.EquipmentRepo }
     * 
     */
    public GDTAF.EquipmentRepo createGDTAFEquipmentRepo() {
        return new GDTAF.EquipmentRepo();
    }

    /**
     * Create an instance of {@link GDTAF.DataElementRepo }
     * 
     */
    public GDTAF.DataElementRepo createGDTAFDataElementRepo() {
        return new GDTAF.DataElementRepo();
    }

    /**
     * Create an instance of {@link ApplicationScenario }
     * 
     */
    public ApplicationScenario createApplicationScenario() {
        return new ApplicationScenario();
    }

    /**
     * Create an instance of {@link OperationalObjective }
     * 
     */
    public OperationalObjective createOperationalObjective() {
        return new OperationalObjective();
    }

    /**
     * Create an instance of {@link OperationalAttribute }
     * 
     */
    public OperationalAttribute createOperationalAttribute() {
        return new OperationalAttribute();
    }

    /**
     * Create an instance of {@link PayloadAttribute }
     * 
     */
    public PayloadAttribute createPayloadAttribute() {
        return new PayloadAttribute();
    }

    /**
     * Create an instance of {@link Payload }
     * 
     */
    public Payload createPayload() {
        return new Payload();
    }

    /**
     * Create an instance of {@link CommunicationSystemRequirement }
     * 
     */
    public CommunicationSystemRequirement createCommunicationSystemRequirement() {
        return new CommunicationSystemRequirement();
    }

    /**
     * Create an instance of {@link BaseBlock }
     * 
     */
    public BaseBlock createBaseBlock() {
        return new BaseBlock();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link ConstrainingAttribute }
     * 
     */
    public ConstrainingAttribute createConstrainingAttribute() {
        return new ConstrainingAttribute();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link DataElement }
     * 
     */
    public DataElement createDataElement() {
        return new DataElement();
    }

    /**
     * Create an instance of {@link TimeContractType }
     * 
     */
    public TimeContractType createTimeContractType() {
        return new TimeContractType();
    }

    /**
     * Create an instance of {@link GridCommunicationPath.EquipNode }
     * 
     */
    public GridCommunicationPath.EquipNode createGridCommunicationPathEquipNode() {
        return new GridCommunicationPath.EquipNode();
    }

    /**
     * Create an instance of {@link GridUseCaseScenario.Overview }
     * 
     */
    public GridUseCaseScenario.Overview createGridUseCaseScenarioOverview() {
        return new GridUseCaseScenario.Overview();
    }

    /**
     * Create an instance of {@link GridUseCaseScenario.Review }
     * 
     */
    public GridUseCaseScenario.Review createGridUseCaseScenarioReview() {
        return new GridUseCaseScenario.Review();
    }

}
