//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 02:05:01 PM MST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://pnnl.gov/gdtaf-gucs", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.inl.igcapt.gdtaf.gucs;
