//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 02:04:59 PM MST 
//


package gov.inl.igcapt.gdtaf.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Asset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Asset"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pnnl.gov/gdtaf-core}BaseBlock"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SourceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ConstrainingAttribute" type="{http://pnnl.gov/gdtaf-core}ConstrainingAttribute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AtLocation" type="{http://pnnl.gov/gdtaf-core}GeoLocation"/&gt;
 *         &lt;element name="EndLocation" type="{http://pnnl.gov/gdtaf-core}GeoLocation" minOccurs="0"/&gt;
 *         &lt;element name="EquipmentZone" type="{http://pnnl.gov/gdtaf-core}CommunicationZone"/&gt;
 *         &lt;element name="EquipmentRole" type="{http://pnnl.gov/gdtaf-core}EquipmentRole"/&gt;
 *         &lt;element name="connected_parents" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="connected_children" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="connected_peers" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="data" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="equipment" type="{http://pnnl.gov/gdtaf-core}guid"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Asset", propOrder = {
    "sourceID",
    "constrainingAttribute",
    "atLocation",
    "endLocation",
    "equipmentZone",
    "equipmentRole",
    "connectedParents",
    "connectedChildren",
    "connectedPeers",
    "data",
    "equipment"
})
@XmlSeeAlso({
    PlanningAsset.class
})
public class Asset
    extends BaseBlock
{

    @XmlElement(name = "SourceID")
    protected String sourceID;
    @XmlElement(name = "ConstrainingAttribute")
    protected List<ConstrainingAttribute> constrainingAttribute;
    @XmlElement(name = "AtLocation", required = true)
    protected GeoLocation atLocation;
    @XmlElement(name = "EndLocation")
    protected GeoLocation endLocation;
    @XmlElement(name = "EquipmentZone", required = true)
    @XmlSchemaType(name = "string")
    protected CommunicationZone equipmentZone;
    @XmlElement(name = "EquipmentRole", required = true)
    @XmlSchemaType(name = "string")
    protected EquipmentRole equipmentRole;
    @XmlElement(name = "connected_parents")
    protected List<String> connectedParents;
    @XmlElement(name = "connected_children")
    protected List<String> connectedChildren;
    @XmlElement(name = "connected_peers")
    protected List<String> connectedPeers;
    protected List<String> data;
    @XmlElement(required = true)
    protected String equipment;

    /**
     * Gets the value of the sourceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceID() {
        return sourceID;
    }

    /**
     * Sets the value of the sourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceID(String value) {
        this.sourceID = value;
    }

    /**
     * Gets the value of the constrainingAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the constrainingAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstrainingAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstrainingAttribute }
     * 
     * 
     */
    public List<ConstrainingAttribute> getConstrainingAttribute() {
        if (constrainingAttribute == null) {
            constrainingAttribute = new ArrayList<ConstrainingAttribute>();
        }
        return this.constrainingAttribute;
    }

    /**
     * Gets the value of the atLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocation }
     *     
     */
    public GeoLocation getAtLocation() {
        return atLocation;
    }

    /**
     * Sets the value of the atLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocation }
     *     
     */
    public void setAtLocation(GeoLocation value) {
        this.atLocation = value;
    }

    /**
     * Gets the value of the endLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocation }
     *     
     */
    public GeoLocation getEndLocation() {
        return endLocation;
    }

    /**
     * Sets the value of the endLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocation }
     *     
     */
    public void setEndLocation(GeoLocation value) {
        this.endLocation = value;
    }

    /**
     * Gets the value of the equipmentZone property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationZone }
     *     
     */
    public CommunicationZone getEquipmentZone() {
        return equipmentZone;
    }

    /**
     * Sets the value of the equipmentZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationZone }
     *     
     */
    public void setEquipmentZone(CommunicationZone value) {
        this.equipmentZone = value;
    }

    /**
     * Gets the value of the equipmentRole property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentRole }
     *     
     */
    public EquipmentRole getEquipmentRole() {
        return equipmentRole;
    }

    /**
     * Sets the value of the equipmentRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentRole }
     *     
     */
    public void setEquipmentRole(EquipmentRole value) {
        this.equipmentRole = value;
    }

    /**
     * Gets the value of the connectedParents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the connectedParents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectedParents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConnectedParents() {
        if (connectedParents == null) {
            connectedParents = new ArrayList<String>();
        }
        return this.connectedParents;
    }

    /**
     * Gets the value of the connectedChildren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the connectedChildren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectedChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConnectedChildren() {
        if (connectedChildren == null) {
            connectedChildren = new ArrayList<String>();
        }
        return this.connectedChildren;
    }

    /**
     * Gets the value of the connectedPeers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the connectedPeers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectedPeers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConnectedPeers() {
        if (connectedPeers == null) {
            connectedPeers = new ArrayList<String>();
        }
        return this.connectedPeers;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getData() {
        if (data == null) {
            data = new ArrayList<String>();
        }
        return this.data;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipment(String value) {
        this.equipment = value;
    }

}
