//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 02:04:59 PM MST 
//


package gov.inl.igcapt.gdtaf.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EquipmentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Communication"/&gt;
 *     &lt;enumeration value="Transmission"/&gt;
 *     &lt;enumeration value="Distribution"/&gt;
 *     &lt;enumeration value="Communication+Transmission"/&gt;
 *     &lt;enumeration value="Communication+Distribution"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EquipmentType", namespace = "http://pnnl.gov/gdtaf-core")
@XmlEnum
public enum EquipmentType {

    @XmlEnumValue("Communication")
    COMMUNICATION("Communication"),
    @XmlEnumValue("Transmission")
    TRANSMISSION("Transmission"),
    @XmlEnumValue("Distribution")
    DISTRIBUTION("Distribution"),
    @XmlEnumValue("Communication+Transmission")
    COMMUNICATION_TRANSMISSION("Communication+Transmission"),
    @XmlEnumValue("Communication+Distribution")
    COMMUNICATION_DISTRIBUTION("Communication+Distribution");
    private final String value;

    EquipmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EquipmentType fromValue(String v) {
        for (EquipmentType c: EquipmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
