//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.02 at 09:17:35 AM MST 
//


package gov.inl.igcapt.gdtaf.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AssetRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Asset" type="{http://pnnl.gov/gdtaf-model}Asset" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CNRMRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CNRM" type="{http://pnnl.gov/gdtaf-model}CNRM" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="TopologyNode" type="{http://pnnl.gov/gdtaf-model}TopologyNode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GridUseCaseScenarioRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="GridUseCaseScenario" type="{http://pnnl.gov/gdtaf-model}GridUseCaseScenario" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ApplicationScenarioRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ApplicationScenario" type="{http://pnnl.gov/gdtaf-model}ApplicationScenario" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OperationalObjectiveRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OperationalObjective" type="{http://pnnl.gov/gdtaf-model}OperationalObjective" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PayloadRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Payload" type="{http://pnnl.gov/gdtaf-model}Payload" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GridCommunicationPathRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="GridCommunicationPath" type="{http://pnnl.gov/gdtaf-model}GridCommunicationPath" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RequirementRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CommunicationSystemRequirement" type="{http://pnnl.gov/gdtaf-model}CommunicationSystemRequirement" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EquipmentRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Equipment" type="{http://pnnl.gov/gdtaf-core}Equipment" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DataElementRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DataElement" type="{http://pnnl.gov/gdtaf-core}DataElement" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ScenarioRepo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Scenario" type="{http://pnnl.gov/gdtaf-model}Scenario" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assetRepo",
    "cnrmRepo",
    "gridUseCaseScenarioRepo",
    "applicationScenarioRepo",
    "operationalObjectiveRepo",
    "payloadRepo",
    "gridCommunicationPathRepo",
    "requirementRepo",
    "equipmentRepo",
    "dataElementRepo",
    "scenarioRepo"
})
@XmlRootElement(name = "GDTAF")
public class GDTAF {

    @XmlElement(name = "AssetRepo")
    protected GDTAF.AssetRepo assetRepo;
    @XmlElement(name = "CNRMRepo")
    protected GDTAF.CNRMRepo cnrmRepo;
    @XmlElement(name = "GridUseCaseScenarioRepo")
    protected GDTAF.GridUseCaseScenarioRepo gridUseCaseScenarioRepo;
    @XmlElement(name = "ApplicationScenarioRepo")
    protected GDTAF.ApplicationScenarioRepo applicationScenarioRepo;
    @XmlElement(name = "OperationalObjectiveRepo")
    protected GDTAF.OperationalObjectiveRepo operationalObjectiveRepo;
    @XmlElement(name = "PayloadRepo")
    protected GDTAF.PayloadRepo payloadRepo;
    @XmlElement(name = "GridCommunicationPathRepo")
    protected GDTAF.GridCommunicationPathRepo gridCommunicationPathRepo;
    @XmlElement(name = "RequirementRepo")
    protected GDTAF.RequirementRepo requirementRepo;
    @XmlElement(name = "EquipmentRepo")
    protected GDTAF.EquipmentRepo equipmentRepo;
    @XmlElement(name = "DataElementRepo")
    protected GDTAF.DataElementRepo dataElementRepo;
    @XmlElement(name = "ScenarioRepo")
    protected GDTAF.ScenarioRepo scenarioRepo;

    /**
     * Gets the value of the assetRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.AssetRepo }
     *     
     */
    public GDTAF.AssetRepo getAssetRepo() {
        return assetRepo;
    }

    /**
     * Sets the value of the assetRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.AssetRepo }
     *     
     */
    public void setAssetRepo(GDTAF.AssetRepo value) {
        this.assetRepo = value;
    }

    /**
     * Gets the value of the cnrmRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.CNRMRepo }
     *     
     */
    public GDTAF.CNRMRepo getCNRMRepo() {
        return cnrmRepo;
    }

    /**
     * Sets the value of the cnrmRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.CNRMRepo }
     *     
     */
    public void setCNRMRepo(GDTAF.CNRMRepo value) {
        this.cnrmRepo = value;
    }

    /**
     * Gets the value of the gridUseCaseScenarioRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.GridUseCaseScenarioRepo }
     *     
     */
    public GDTAF.GridUseCaseScenarioRepo getGridUseCaseScenarioRepo() {
        return gridUseCaseScenarioRepo;
    }

    /**
     * Sets the value of the gridUseCaseScenarioRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.GridUseCaseScenarioRepo }
     *     
     */
    public void setGridUseCaseScenarioRepo(GDTAF.GridUseCaseScenarioRepo value) {
        this.gridUseCaseScenarioRepo = value;
    }

    /**
     * Gets the value of the applicationScenarioRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.ApplicationScenarioRepo }
     *     
     */
    public GDTAF.ApplicationScenarioRepo getApplicationScenarioRepo() {
        return applicationScenarioRepo;
    }

    /**
     * Sets the value of the applicationScenarioRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.ApplicationScenarioRepo }
     *     
     */
    public void setApplicationScenarioRepo(GDTAF.ApplicationScenarioRepo value) {
        this.applicationScenarioRepo = value;
    }

    /**
     * Gets the value of the operationalObjectiveRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.OperationalObjectiveRepo }
     *     
     */
    public GDTAF.OperationalObjectiveRepo getOperationalObjectiveRepo() {
        return operationalObjectiveRepo;
    }

    /**
     * Sets the value of the operationalObjectiveRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.OperationalObjectiveRepo }
     *     
     */
    public void setOperationalObjectiveRepo(GDTAF.OperationalObjectiveRepo value) {
        this.operationalObjectiveRepo = value;
    }

    /**
     * Gets the value of the payloadRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.PayloadRepo }
     *     
     */
    public GDTAF.PayloadRepo getPayloadRepo() {
        return payloadRepo;
    }

    /**
     * Sets the value of the payloadRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.PayloadRepo }
     *     
     */
    public void setPayloadRepo(GDTAF.PayloadRepo value) {
        this.payloadRepo = value;
    }

    /**
     * Gets the value of the gridCommunicationPathRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.GridCommunicationPathRepo }
     *     
     */
    public GDTAF.GridCommunicationPathRepo getGridCommunicationPathRepo() {
        return gridCommunicationPathRepo;
    }

    /**
     * Sets the value of the gridCommunicationPathRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.GridCommunicationPathRepo }
     *     
     */
    public void setGridCommunicationPathRepo(GDTAF.GridCommunicationPathRepo value) {
        this.gridCommunicationPathRepo = value;
    }

    /**
     * Gets the value of the requirementRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.RequirementRepo }
     *     
     */
    public GDTAF.RequirementRepo getRequirementRepo() {
        return requirementRepo;
    }

    /**
     * Sets the value of the requirementRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.RequirementRepo }
     *     
     */
    public void setRequirementRepo(GDTAF.RequirementRepo value) {
        this.requirementRepo = value;
    }

    /**
     * Gets the value of the equipmentRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.EquipmentRepo }
     *     
     */
    public GDTAF.EquipmentRepo getEquipmentRepo() {
        return equipmentRepo;
    }

    /**
     * Sets the value of the equipmentRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.EquipmentRepo }
     *     
     */
    public void setEquipmentRepo(GDTAF.EquipmentRepo value) {
        this.equipmentRepo = value;
    }

    /**
     * Gets the value of the dataElementRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.DataElementRepo }
     *     
     */
    public GDTAF.DataElementRepo getDataElementRepo() {
        return dataElementRepo;
    }

    /**
     * Sets the value of the dataElementRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.DataElementRepo }
     *     
     */
    public void setDataElementRepo(GDTAF.DataElementRepo value) {
        this.dataElementRepo = value;
    }

    /**
     * Gets the value of the scenarioRepo property.
     * 
     * @return
     *     possible object is
     *     {@link GDTAF.ScenarioRepo }
     *     
     */
    public GDTAF.ScenarioRepo getScenarioRepo() {
        return scenarioRepo;
    }

    /**
     * Sets the value of the scenarioRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDTAF.ScenarioRepo }
     *     
     */
    public void setScenarioRepo(GDTAF.ScenarioRepo value) {
        this.scenarioRepo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ApplicationScenario" type="{http://pnnl.gov/gdtaf-model}ApplicationScenario" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicationScenario"
    })
    public static class ApplicationScenarioRepo {

        @XmlElement(name = "ApplicationScenario", required = true)
        protected List<ApplicationScenario> applicationScenario;

        /**
         * Gets the value of the applicationScenario property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the applicationScenario property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicationScenario().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicationScenario }
         * 
         * 
         */
        public List<ApplicationScenario> getApplicationScenario() {
            if (applicationScenario == null) {
                applicationScenario = new ArrayList<ApplicationScenario>();
            }
            return this.applicationScenario;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Asset" type="{http://pnnl.gov/gdtaf-model}Asset" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asset"
    })
    public static class AssetRepo {

        @XmlElement(name = "Asset")
        protected List<Asset> asset;

        /**
         * Gets the value of the asset property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the asset property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAsset().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Asset }
         * 
         * 
         */
        public List<Asset> getAsset() {
            if (asset == null) {
                asset = new ArrayList<Asset>();
            }
            return this.asset;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CNRM" type="{http://pnnl.gov/gdtaf-model}CNRM" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="TopologyNode" type="{http://pnnl.gov/gdtaf-model}TopologyNode" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cnrm",
        "topologyNode"
    })
    public static class CNRMRepo {

        @XmlElement(name = "CNRM")
        protected List<CNRM> cnrm;
        @XmlElement(name = "TopologyNode")
        protected List<TopologyNode> topologyNode;

        /**
         * Gets the value of the cnrm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the cnrm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCNRM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CNRM }
         * 
         * 
         */
        public List<CNRM> getCNRM() {
            if (cnrm == null) {
                cnrm = new ArrayList<CNRM>();
            }
            return this.cnrm;
        }

        /**
         * Gets the value of the topologyNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the topologyNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTopologyNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TopologyNode }
         * 
         * 
         */
        public List<TopologyNode> getTopologyNode() {
            if (topologyNode == null) {
                topologyNode = new ArrayList<TopologyNode>();
            }
            return this.topologyNode;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DataElement" type="{http://pnnl.gov/gdtaf-core}DataElement" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataElement"
    })
    public static class DataElementRepo {

        @XmlElement(name = "DataElement", required = true)
        protected List<DataElement> dataElement;

        /**
         * Gets the value of the dataElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the dataElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataElement }
         * 
         * 
         */
        public List<DataElement> getDataElement() {
            if (dataElement == null) {
                dataElement = new ArrayList<DataElement>();
            }
            return this.dataElement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Equipment" type="{http://pnnl.gov/gdtaf-core}Equipment" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equipment"
    })
    public static class EquipmentRepo {

        @XmlElement(name = "Equipment", required = true)
        protected List<Equipment> equipment;

        /**
         * Gets the value of the equipment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the equipment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEquipment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Equipment }
         * 
         * 
         */
        public List<Equipment> getEquipment() {
            if (equipment == null) {
                equipment = new ArrayList<Equipment>();
            }
            return this.equipment;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="GridCommunicationPath" type="{http://pnnl.gov/gdtaf-model}GridCommunicationPath" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gridCommunicationPath"
    })
    public static class GridCommunicationPathRepo {

        @XmlElement(name = "GridCommunicationPath", required = true)
        protected List<GridCommunicationPath> gridCommunicationPath;

        /**
         * Gets the value of the gridCommunicationPath property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the gridCommunicationPath property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGridCommunicationPath().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GridCommunicationPath }
         * 
         * 
         */
        public List<GridCommunicationPath> getGridCommunicationPath() {
            if (gridCommunicationPath == null) {
                gridCommunicationPath = new ArrayList<GridCommunicationPath>();
            }
            return this.gridCommunicationPath;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="GridUseCaseScenario" type="{http://pnnl.gov/gdtaf-model}GridUseCaseScenario" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gridUseCaseScenario"
    })
    public static class GridUseCaseScenarioRepo {

        @XmlElement(name = "GridUseCaseScenario", required = true)
        protected List<GridUseCaseScenario> gridUseCaseScenario;

        /**
         * Gets the value of the gridUseCaseScenario property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the gridUseCaseScenario property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGridUseCaseScenario().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GridUseCaseScenario }
         * 
         * 
         */
        public List<GridUseCaseScenario> getGridUseCaseScenario() {
            if (gridUseCaseScenario == null) {
                gridUseCaseScenario = new ArrayList<GridUseCaseScenario>();
            }
            return this.gridUseCaseScenario;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OperationalObjective" type="{http://pnnl.gov/gdtaf-model}OperationalObjective" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operationalObjective"
    })
    public static class OperationalObjectiveRepo {

        @XmlElement(name = "OperationalObjective", required = true)
        protected List<OperationalObjective> operationalObjective;

        /**
         * Gets the value of the operationalObjective property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the operationalObjective property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperationalObjective().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OperationalObjective }
         * 
         * 
         */
        public List<OperationalObjective> getOperationalObjective() {
            if (operationalObjective == null) {
                operationalObjective = new ArrayList<OperationalObjective>();
            }
            return this.operationalObjective;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Payload" type="{http://pnnl.gov/gdtaf-model}Payload" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payload"
    })
    public static class PayloadRepo {

        @XmlElement(name = "Payload", required = true)
        protected List<Payload> payload;

        /**
         * Gets the value of the payload property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the payload property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPayload().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Payload }
         * 
         * 
         */
        public List<Payload> getPayload() {
            if (payload == null) {
                payload = new ArrayList<Payload>();
            }
            return this.payload;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CommunicationSystemRequirement" type="{http://pnnl.gov/gdtaf-model}CommunicationSystemRequirement" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "communicationSystemRequirement"
    })
    public static class RequirementRepo {

        @XmlElement(name = "CommunicationSystemRequirement", required = true)
        protected List<CommunicationSystemRequirement> communicationSystemRequirement;

        /**
         * Gets the value of the communicationSystemRequirement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the communicationSystemRequirement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCommunicationSystemRequirement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommunicationSystemRequirement }
         * 
         * 
         */
        public List<CommunicationSystemRequirement> getCommunicationSystemRequirement() {
            if (communicationSystemRequirement == null) {
                communicationSystemRequirement = new ArrayList<CommunicationSystemRequirement>();
            }
            return this.communicationSystemRequirement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Scenario" type="{http://pnnl.gov/gdtaf-model}Scenario" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scenario"
    })
    public static class ScenarioRepo {

        @XmlElement(name = "Scenario", required = true)
        protected List<Scenario> scenario;

        /**
         * Gets the value of the scenario property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the scenario property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScenario().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Scenario }
         * 
         * 
         */
        public List<Scenario> getScenario() {
            if (scenario == null) {
                scenario = new ArrayList<Scenario>();
            }
            return this.scenario;
        }

    }

}
