//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 02:04:59 PM MST 
//


package gov.inl.igcapt.gdtaf.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GridUseCaseScenario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridUseCaseScenario"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pnnl.gov/gdtaf-core}BaseBlock"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Overview" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Review" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                 &lt;/all&gt;
 *                 &lt;attribute name="Reviewer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="app_scenarios" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded"/&gt;
 *         &lt;element name="payloads" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded"/&gt;
 *         &lt;element name="reqs" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded"/&gt;
 *         &lt;element name="path_options" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="MaximumLinkScore" type="{http://pnnl.gov/gdtaf-core}LinkScore" /&gt;
 *       &lt;attribute name="Approved" type="{http://pnnl.gov/gdtaf-model}ApprovedState" default="Not_Approved" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridUseCaseScenario", propOrder = {
    "overview",
    "description",
    "review",
    "appScenarios",
    "payloads",
    "reqs",
    "pathOptions"
})
public class GridUseCaseScenario
    extends BaseBlock
{

    @XmlElement(name = "Overview", required = true)
    protected String overview;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Review")
    protected List<GridUseCaseScenario.Review> review;
    @XmlElement(name = "app_scenarios", required = true)
    protected List<String> appScenarios;
    @XmlElement(required = true)
    protected List<String> payloads;
    @XmlElement(required = true)
    protected List<String> reqs;
    @XmlElement(name = "path_options", required = true)
    protected List<String> pathOptions;
    @XmlAttribute(name = "MaximumLinkScore")
    protected Double maximumLinkScore;
    @XmlAttribute(name = "Approved")
    protected ApprovedState approved;

    /**
     * Gets the value of the overview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverview() {
        return overview;
    }

    /**
     * Sets the value of the overview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverview(String value) {
        this.overview = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the review property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the review property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReview().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GridUseCaseScenario.Review }
     * 
     * 
     */
    public List<GridUseCaseScenario.Review> getReview() {
        if (review == null) {
            review = new ArrayList<GridUseCaseScenario.Review>();
        }
        return this.review;
    }

    /**
     * Gets the value of the appScenarios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the appScenarios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppScenarios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAppScenarios() {
        if (appScenarios == null) {
            appScenarios = new ArrayList<String>();
        }
        return this.appScenarios;
    }

    /**
     * Gets the value of the payloads property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the payloads property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayloads().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPayloads() {
        if (payloads == null) {
            payloads = new ArrayList<String>();
        }
        return this.payloads;
    }

    /**
     * Gets the value of the reqs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the reqs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReqs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReqs() {
        if (reqs == null) {
            reqs = new ArrayList<String>();
        }
        return this.reqs;
    }

    /**
     * Gets the value of the pathOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the pathOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPathOptions() {
        if (pathOptions == null) {
            pathOptions = new ArrayList<String>();
        }
        return this.pathOptions;
    }

    /**
     * Gets the value of the maximumLinkScore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximumLinkScore() {
        return maximumLinkScore;
    }

    /**
     * Sets the value of the maximumLinkScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximumLinkScore(Double value) {
        this.maximumLinkScore = value;
    }

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovedState }
     *     
     */
    public ApprovedState getApproved() {
        if (approved == null) {
            return ApprovedState.NOT_APPROVED;
        } else {
            return approved;
        }
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovedState }
     *     
     */
    public void setApproved(ApprovedState value) {
        this.approved = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *       &lt;/all&gt;
     *       &lt;attribute name="Reviewer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Review {

        @XmlAttribute(name = "Reviewer", required = true)
        protected String reviewer;
        @XmlAttribute(name = "Date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the reviewer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReviewer() {
            return reviewer;
        }

        /**
         * Sets the value of the reviewer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReviewer(String value) {
            this.reviewer = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

    }

}
