//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.02 at 09:17:35 AM MST 
//


package gov.inl.igcapt.gdtaf.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SolutionAsset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolutionAsset"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pnnl.gov/gdtaf-model}PlanningAsset"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Views" type="{http://pnnl.gov/gdtaf-model}SolutionAssetView" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="associated_gucs" type="{http://pnnl.gov/gdtaf-core}guid"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolutionAsset", propOrder = {
    "views",
    "associatedGucs"
})
public class SolutionAsset
    extends PlanningAsset
{

    @XmlElement(name = "Views")
    protected List<SolutionAssetView> views;
    @XmlElement(name = "associated_gucs", required = true)
    protected String associatedGucs;

    /**
     * Gets the value of the views property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the views property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViews().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolutionAssetView }
     * 
     * 
     */
    public List<SolutionAssetView> getViews() {
        if (views == null) {
            views = new ArrayList<SolutionAssetView>();
        }
        return this.views;
    }

    /**
     * Gets the value of the associatedGucs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedGucs() {
        return associatedGucs;
    }

    /**
     * Sets the value of the associatedGucs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedGucs(String value) {
        this.associatedGucs = value;
    }

}
