//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.02 at 09:17:35 AM MST 
//


package gov.inl.igcapt.gdtaf.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SolutionOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolutionOption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pnnl.gov/gdtaf-core}BaseBlock"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaximumLinkScore" type="{http://pnnl.gov/gdtaf-core}LinkScore" minOccurs="0"/&gt;
 *         &lt;element name="SolutionAsset" type="{http://pnnl.gov/gdtaf-model}SolutionAsset" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Exception" type="{http://pnnl.gov/gdtaf-model}SolutionException" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Node" type="{http://pnnl.gov/gdtaf-model}TopologyNode" maxOccurs="unbounded"/&gt;
 *         &lt;element name="cnrm_head" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="gucs_head" type="{http://pnnl.gov/gdtaf-core}guid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="parent" type="{http://pnnl.gov/gdtaf-core}guid" /&gt;
 *       &lt;attribute name="topology_head" type="{http://pnnl.gov/gdtaf-core}guid" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolutionOption", propOrder = {
    "maximumLinkScore",
    "solutionAsset",
    "exception",
    "node",
    "cnrmHead",
    "gucsHead"
})
public class SolutionOption
    extends BaseBlock
{

    @XmlElement(name = "MaximumLinkScore")
    protected Double maximumLinkScore;
    @XmlElement(name = "SolutionAsset", required = true)
    protected List<SolutionAsset> solutionAsset;
    @XmlElement(name = "Exception")
    protected List<SolutionException> exception;
    @XmlElement(name = "Node", required = true)
    protected List<TopologyNode> node;
    @XmlElement(name = "cnrm_head")
    protected List<String> cnrmHead;
    @XmlElement(name = "gucs_head")
    protected List<String> gucsHead;
    @XmlAttribute(name = "parent")
    protected String parent;
    @XmlAttribute(name = "topology_head")
    protected String topologyHead;

    /**
     * Gets the value of the maximumLinkScore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximumLinkScore() {
        return maximumLinkScore;
    }

    /**
     * Sets the value of the maximumLinkScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximumLinkScore(Double value) {
        this.maximumLinkScore = value;
    }

    /**
     * Gets the value of the solutionAsset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the solutionAsset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSolutionAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolutionAsset }
     * 
     * 
     */
    public List<SolutionAsset> getSolutionAsset() {
        if (solutionAsset == null) {
            solutionAsset = new ArrayList<SolutionAsset>();
        }
        return this.solutionAsset;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolutionException }
     * 
     * 
     */
    public List<SolutionException> getException() {
        if (exception == null) {
            exception = new ArrayList<SolutionException>();
        }
        return this.exception;
    }

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TopologyNode }
     * 
     * 
     */
    public List<TopologyNode> getNode() {
        if (node == null) {
            node = new ArrayList<TopologyNode>();
        }
        return this.node;
    }

    /**
     * Gets the value of the cnrmHead property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the cnrmHead property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCnrmHead().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCnrmHead() {
        if (cnrmHead == null) {
            cnrmHead = new ArrayList<String>();
        }
        return this.cnrmHead;
    }

    /**
     * Gets the value of the gucsHead property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the gucsHead property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGucsHead().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGucsHead() {
        if (gucsHead == null) {
            gucsHead = new ArrayList<String>();
        }
        return this.gucsHead;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the topologyHead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopologyHead() {
        return topologyHead;
    }

    /**
     * Sets the value of the topologyHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopologyHead(String value) {
        this.topologyHead = value;
    }

}
