/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gov.inl.igcapt.wizard;

//import com.fasterxml.jackson.core.JsonGenerator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import com.fasterxml.jackson.databind.type.TypeFactory;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import org.json.JSONArray;
import org.json.JSONObject;
import org.openstreetmap.gui.jmapviewer.IGCAPTgui;
import org.openstreetmap.gui.jmapviewer.IGCAPTproperties;
/**
 *
 * @author CHE
 */
public class AddToScenarioWizard extends javax.swing.JDialog {
    private List<GucsInformation>m_gucsList;
    private List<CnrmInformation>m_cnrmList;
    private final ScenarioInformation m_newScenarioInfo;
    private String m_webServiceHost;
    private String m_webServiceKey;
    enum ButtonStages {
        LINE1,   // Enable first line
        LINE2,   // Enable Second line
        LINE3    // enable Third line
    }
    
    /**
     * Creates new form ScenarioWizard
     */
    public AddToScenarioWizard(java.awt.Frame parent, boolean modal, ScenarioInformation newScenario) {
        super(parent, modal);
        m_webServiceHost = IGCAPTproperties.getInstance().getPropertyKeyValue("WebServiceHost");
        m_webServiceKey = IGCAPTproperties.getInstance().getPropertyKeyValue("WebServiceKey");
        m_newScenarioInfo = newScenario;
        initComponents();
        initComboBoxes();
        disableEnableButtons(ButtonStages.LINE1);
        this.setVisible(true);
    }
    
    private void disableLine1() {
        
    }
    
    private void disableLine2() {
        
    }
    
    private void disableLine3() {
        
    }
    
    private void disableEnableButtons(ButtonStages stage) {
        switch (stage) {
            case LINE1:
                disableLine2();
                disableLine3();
                break;
            case LINE2:
                disableLine1();
                disableLine3();
                break;
            case LINE3:
                disableLine1();
                disableLine2();
                break;
        }
        
        if (stage.equals(ButtonStages.LINE1))
        if (!m_gucsList.isEmpty() && !m_cnrmList.isEmpty() && !jTextField1.getText().isEmpty()) {
            jButton2.setEnabled(true);
        }
        else {
            jButton2.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Scenario with GUCS/CNRM");

        jLabel1.setText("Select GUCS");
        jLabel1.setToolTipText("");

        jLabel2.setText("Select CNRM");

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.setToolTipText("Delete scenario and quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Save Location");
        jLabel3.setToolTipText("Select Location for the Scenario file");

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, 299, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initComboBoxes() {
        m_gucsList = getGucsList();
        m_cnrmList = getCnrmList();
        String[] stringArray = new String[m_gucsList.size()];
        int count=0;
        for (GucsInformation gucs : m_gucsList) {
            stringArray[count++] = gucs.getName();
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(stringArray));        
        stringArray = new String[m_cnrmList.size()];
        count=0;
        for (CnrmInformation cnrm : m_cnrmList) {
            stringArray[count++] = cnrm.getName();
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(stringArray));
        
    }
    
    private List<GucsInformation> getGucsList() {
        String output;
        try {
            URL url = new URL("https://" + m_webServiceHost + 
                    "/core/gucs?subscription-key=" + m_webServiceKey);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");
            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }
            
            InputStreamReader in = new InputStreamReader(conn.getInputStream());
            BufferedReader br = new BufferedReader(in);
            ObjectMapper objMapper = new ObjectMapper();
            TypeFactory typeFactory = objMapper.getTypeFactory();
            CollectionType collectionType = typeFactory.constructCollectionType(List.class, GucsInformation.class);
            while ((output = br.readLine()) != null) {
                m_gucsList = objMapper.readValue(output, collectionType);
            }
            conn.disconnect();
            // at this point need to parse the results and add to the combo
        }
        catch (Exception e2) {
            System.out.println("Exception!"+e2.getMessage());
        }
        return m_gucsList;
    }
    
    private List<CnrmInformation> getCnrmList() {
        String output;
        try {
            URL url = new URL("https://" + m_webServiceHost + 
                    "/core/cnrm?subscription-key=" + m_webServiceKey);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");
            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }
            
            InputStreamReader in = new InputStreamReader(conn.getInputStream());
            BufferedReader br = new BufferedReader(in);
            ObjectMapper objMapper = new ObjectMapper();
            TypeFactory typeFactory = objMapper.getTypeFactory();
            CollectionType collectionType = typeFactory.constructCollectionType(List.class, CnrmInformation.class);
            while ((output = br.readLine()) != null) {
                m_cnrmList = objMapper.readValue(output, collectionType);
            }
            conn.disconnect();
            // at this point need to parse the results and add to the combo
        }
        catch (Exception e2) {
            System.out.println("Exception!"+e2.getMessage());
        }
        return m_cnrmList;
    }
    
    private void updateScenarioGucsList() {
        JSONArray jsonArray = new JSONArray();
        // This will need to be updated to pick multiples but for now just one
        int index = jComboBox1.getSelectedIndex();
        GucsInformation selectedGucs = m_gucsList.get(index);
        jsonArray.put(selectedGucs.getId());
        String scenarioId = m_newScenarioInfo.getId();

        try {
            String urlString = "https://" + m_webServiceHost + 
                    "/core/scenarios/" + scenarioId + "/gucs?subscription-key=" +
                    m_webServiceKey; 
            URL url = new URL(urlString);
            
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setDoOutput(true);
            conn.setRequestMethod("PUT");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setRequestProperty("Accept", "application/json");
            
            OutputStream os = conn.getOutputStream();
            byte[] input = jsonArray.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
            if (conn.getResponseCode() != 200) {
                System.out.println("Message=="+conn.getResponseMessage());
                System.out.println("Bad response code=="+conn.getResponseCode());
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }       
                        
            InputStreamReader isr = new InputStreamReader(conn.getInputStream(), "utf-8");
            BufferedReader br = new BufferedReader(isr);
            ObjectMapper objMapper = new ObjectMapper();
            
            String response = br.readLine();
            if (conn.getResponseCode() != 200) { 
                ProblemDetails problemDetails = objMapper.readValue(response, ProblemDetails.class);
                System.out.println(problemDetails.toString());
            }
                
            conn.disconnect();
        }
        catch (Exception e2) {
            System.out.println(e2.getMessage());
        }
    }
    
    private void updateScenarioCnrmList() {
        JSONArray jsonArray = new JSONArray();
        // This will need to be updated to pick multiples but for now just one
        int index = jComboBox2.getSelectedIndex();
        CnrmInformation selectedCnrm = m_cnrmList.get(index);
        jsonArray.put(selectedCnrm.getId());
        String scenarioId = m_newScenarioInfo.getId();

        try {
            String urlString = "https://" + m_webServiceHost + 
                    "/core/scenarios/" + scenarioId + "/cnrm?subscription-key=" + 
                    m_webServiceKey;
            URL url = new URL(urlString);
            
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setDoOutput(true);
            conn.setRequestMethod("PUT");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setRequestProperty("Accept", "application/json");
            
            OutputStream os = conn.getOutputStream();
            byte[] input = jsonArray.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
            if (conn.getResponseCode() != 200) {
                System.out.println("Message=="+conn.getResponseMessage());
                System.out.println("Bad response code=="+conn.getResponseCode());
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }       
                        
            InputStreamReader isr = new InputStreamReader(conn.getInputStream(), "utf-8");
            BufferedReader br = new BufferedReader(isr);
            ObjectMapper objMapper = new ObjectMapper();
            
            String response = br.readLine();
            if (conn.getResponseCode() != 200) { 
                ProblemDetails problemDetails = objMapper.readValue(response, ProblemDetails.class);
                System.out.println(problemDetails.toString());
            }
                
            conn.disconnect();
        }
        catch (Exception e2) {
            System.out.println(e2.getMessage());
        }
    }

    // For now write the scenario file to the "LastPath" property locations
    // Name the file scenarioInformation.getName()
    private void writeScenarioFile(ScenarioDetails scenarioDetails) {
        // Cherie - get new path here
        String lastPath = IGCAPTproperties.getInstance().getPropertyKeyValue("LastPath");
        // strip off the filename
        int index = lastPath.lastIndexOf(File.separator);
        lastPath = lastPath.substring(0, index);
        String scenarioFile = lastPath + File.separator + 
            scenarioDetails.getScenarioInformation().getName() + ".xml";
        try {
            
            PrintWriter writer = new PrintWriter(scenarioFile, "UTF-8");
            writer.println(scenarioDetails.getContent());
            writer.close();
        }
        catch (Exception e) {
            System.out.println("Exception:"+e.getMessage());
        }
    }
    
    private void getTheScenarioFile() {
        String output;
        ScenarioDetails scenarioDetails = null;
        try {
            URL url = new URL("https://" + m_webServiceHost + "/core/scenarios/" +
                    m_newScenarioInfo.getId() + "?subscription-key=" + 
                    m_webServiceKey);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");
            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }
            
            InputStreamReader in = new InputStreamReader(conn.getInputStream());
            BufferedReader br = new BufferedReader(in);
            ObjectMapper objMapper = new ObjectMapper();
            while ((output = br.readLine()) != null) {
                scenarioDetails = objMapper.readValue(output, ScenarioDetails.class);
            }
            if (scenarioDetails != null) {
                writeScenarioFile(scenarioDetails);
            }
            conn.disconnect();
            // at this point need to parse the results and add to the combo
        }
        catch (Exception e2) {
            System.out.println("Exception!"+e2.getMessage());
            //return e2.getMessage();
        }
    }
       
    /*private void cleanupScenarios() {
        String output;
        List<ScenarioInformation>scenarioList = null;
        ScenarioInformation scenarioInformation = null;
        try {
            URL url = new URL("https://" + m_webServiceHost + "/core/scenarios" +
                              "?subscription-key=" + m_webServiceKey);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");
            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed : HTTP Error code : "+ conn.getResponseCode());
            }
            
            InputStreamReader in = new InputStreamReader(conn.getInputStream());
            BufferedReader br = new BufferedReader(in);
            ObjectMapper objMapper = new ObjectMapper();
            TypeFactory typeFactory = objMapper.getTypeFactory();
            CollectionType collectionType = typeFactory.constructCollectionType(List.class, ScenarioInformation.class);
            while ((output = br.readLine()) != null) {
                scenarioList = objMapper.readValue(output, collectionType);
            }
            conn.disconnect();
            // at this point need to parse the results and add to the combo
        }
        catch (Exception e2) {
            System.out.println("Exception!"+e2.getMessage());
            //return e2.getMessage();
        }
        if (scenarioList != null) {
            for (ScenarioInformation scenario : scenarioList) {
                if (scenario.getName().startsWith("Test")) {
                    System.out.println("Delete scenario named:"+scenario.getName());
                    deleteScenario(scenario.getId());
                }
            }
        }
    }*/

    // delete scenario due to cancelling wizard
    private void deleteScenario(String id) {
        JSONObject json = new JSONObject();
        json.put("id", id);
        HttpURLConnection conn = null;
        try {
            URL url = new URL("https://" + m_webServiceHost + "/core/scenarios/"
                + id + "?subscription-key=" + m_webServiceKey);
            
            conn = (HttpURLConnection)url.openConnection();
            conn.setRequestMethod("DELETE");
            conn.setRequestProperty("Accept", "application/json");
            conn.setDoOutput(true);
            
            OutputStream os = conn.getOutputStream();
            byte[] input = json.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Failed: HTTP Error code:"+conn.getResponseCode());
            }
        }
        catch (Exception e) {
            System.out.println("Exception::"+e.getMessage());
        }
        if (conn != null) {
            conn.disconnect();
        }
    }

    // Next button - Select GUCS
    // PUT to update the list of GUCS for the scenario  -- need scneario id and gucs id(s)
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateScenarioGucsList();
        //cleanupScenarios(); //-- this is test code
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Cancel - delete the scenario and close form
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deleteScenario(m_newScenarioInfo.getId());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Browse button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        String lastPath = IGCAPTgui.getInstance().getLastPath(); 
        if (lastPath != null && !lastPath.isEmpty()) {
            File lastPath1 = new File(lastPath);
            if (lastPath1.exists()) {
                chooser.setCurrentDirectory(lastPath1);
            }
        }
        
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextField1.setText(chooser.getSelectedFile().toString());
            if (jTextField1.getText() != null) {
                jButton2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Next button - Select CNRM
    // PUT to update the list of CNRM for the scenario -- need scenario id and cnrm id(s)
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        updateScenarioCnrmList();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Next button - Browse to Scenario location
    // Get to get the scenario file and write it to file system.
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        getTheScenarioFile();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToScenarioWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToScenarioWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToScenarioWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToScenarioWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Scenario hard coded for testing
                ScenarioInformation scenario = new ScenarioInformation();
                scenario.setId("_1ee34d83-8fe3-4ad2-9757-d718b4218040");
                scenario.setName("newTest1");
                scenario.setSourceId("_1ee34d83-8fe3-4ad2-9757-d718b4218040");
                AddToScenarioWizard dialog = new AddToScenarioWizard(new javax.swing.JFrame(), true, scenario);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
